version: 2.1
  
jobs:
  docker-executor-with-non-auth:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "show a warning message in the spinup step"
  docker-executor-with-auth:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo "no warning message"
workflows:
  version: 2
  workflow:
    jobs:
      - docker-executor-with-non-auth
      - docker-executor-with-auth
