version: 2
  
jobs:
  docker-executor-with-non-auth:
    docker:
      - image: circleci/node:latest
    steps:
      - run: echo "show a warning message in the spinup step"
  docker-executor-with-auth:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: echo "no warning message"
  docker-executor-with-wrong-password:
    docker:
      - image: circleci/node:latest
        auth:
          username: $DOCKERHUB_USER
          password: "hello"
    steps:
      - run: echo "failed to spin up"
  docker-executor-private-image:
    docker:
      - image: takamaru/private-image-test:latest
    steps:
      - run: echo "failed to spin up"
  machine-executor-pull-private-image:
    machine: true
    steps:
      - run: docker pull takamaru/private-image-test:latest

workflows:
  version: 2
  workflow:
    jobs:
      - docker-executor-with-non-auth
      - docker-executor-with-auth
      - docker-executor-with-wrong-password
      - docker-executor-private-image
      - machine-executor-pull-private-image
